## Numpy Arrays

* It provides extension package to multidimensional arrays
* Closer to hardware
* Designed for scientific computation
* It is known as array Oriented computing
* It take very less space
* NumPy have optimized functions such as linear algebra operations built in
* Very fast 


In [1]:
import numpy as np

In [2]:
z=np.arange(1,10,1) # creating array using arange function start,end,step like seq in r programming
print(z)

l=np.arange(10)  # start from 0
print(l)

x=np.array([0,1,2,3,4,5,]) #directly providing the data in a list
print(x)

[1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5]


In [3]:
p=np.array([[1,2,3],[3,4,5]]) #2d array
print(p)

[[1 2 3]
 [3 4 5]]


In [4]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)

[1 2 3 4]
1


In [5]:
p=a[:,np.newaxis] # newaxis increase the dimensionality
print(p)
print(p.ndim)

[[1]
 [2]
 [3]
 [4]]
2


In [6]:
a1=np.arange(1,40,2) # staring with 1 ,ending with 39 and step size is 2
print(a1)
print(a1.shape)     # shape of the numpy array



a1=a1.reshape(5,4) # changing the shape of the numoy array
print(a1)
print(a1.shape) # 5 rowsa and 4 columns

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
(20,)
[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]
(5, 4)


In [7]:
x=a1.ravel() #ravel function is used for flatterning (flattening from 5d to 1d)
print(x)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


## Measuring performance (Time)

* genearting squares for each number from 0 to 999 with list
* generating squares for each number from 0 to 999 with numpy array 

In [8]:
l=range(1000) # starts from 0 and ending with 999
%timeit [i*i for i in l] 

119 µs ± 4.28 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [9]:
l=np.arange(1000) # starts from 0 and end with 999
%timeit l**2

2.72 µs ± 119 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
x=np.array([1,2,3,4])
print(x)

x=x+1 #1 is a scaler 1 is added to all all elements of x
print(x)

x=x*2 # multiplication of each elemnt in x with 2
print(x)

[1 2 3 4]
[2 3 4 5]
[ 4  6  8 10]


In [11]:
b=np.ones(4)+1 # creating numy array with ones of size 4 and adding scalr value 1 to it
print(b)

[2. 2. 2. 2.]


In [12]:
c=np.ones((3,4,4)) #all zeros with 3 matrics ----4 rows and 4 columns
c

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [13]:
print(b*c) #numpy array multiplication

print(b-c) # numpy array subtraction


[[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [14]:
d=np.diag([1,2,3,4]) # creating a diagonal matrix 
print(d)

print(d*d) # multiplying matrix with itself

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


### element wise  comparison

In [15]:
a=np.array([1,2,3,4]) 
b=np.array([0,2,3,4])
print(a==b) 
print(a!=b) 
print(a>b)

[False  True  True  True]
[ True False False False]
[ True False False False]


### array comparision

In [16]:
a=np.array([1,2,34,4])
b=np.array([1,2,35,4])
c=np.array([1,2,34,4])
print(np.array_equal(a,b))
print(np.array_equal(a,c))

False
True


### logical operator


In [17]:
a=np.array([1,0,0,1])
b=np.array([0,1,1,0])
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True]
[False False False False]


### transcendental function


In [18]:
a=np.array([1,2,3,4,5])
print(np.sin(a)) 
print(np.log(a))
print(np.exp(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [19]:
a+np.array([1]) # replication happend when it matches rows or columns with the before matrix

array([2, 3, 4, 5, 6])

In [20]:
#a+np.array([[1,2]]) replication not happend

In [21]:
x=np.arange(1,12,2)
print(x)

print(np.sum(x))

[ 1  3  5  7  9 11]
36


In [22]:
y=x.reshape(3,2)
y

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [23]:
y.T #transpose

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [24]:
x=np.arange(20)
print(x)
x=x.reshape(5,4)
print("******************")
print(x)
print("******************")
print(np.sum(x,axis=0))    #column wise sum
print("******************")
print(np.sum(x,axis=1))    #row wise sum 
#print(np.sum(x))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
******************
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
******************
[40 45 50 55]
******************
[ 6 22 38 54 70]


In [25]:
a2=np.arange(4*3*2)  # creating numpy array with 0 to 23
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [26]:
a3=np.arange(4*3*2).reshape(4,6) #reshaping
print(a3)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [27]:
a3=np.arange(4*3*2).reshape(4,3,2) # 4 matrices with 3 rows and 2 columns from o to 23 numbers
print(a3)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [28]:
           # Accesing the data from numpy array
a3[0,2,1]  # 0th matrix 2nd row 1st column (index starts from 0)

5

* Both reshape and resize change the shape of the numpy array
* the difference is that using resize will affect the original array while using reshape create a new reshaped instance of the array.

In [29]:
a=np.arange(4)
print(a)

a.resize((7,))
print(a)

a.resize((8,))  
print(a)

a.resize((12,))
print(a)

a.resize((2,))
print(a)

a.resize((3,))
print(a)



[0 1 2 3]
[0 1 2 3 0 0 0]
[0 1 2 3 0 0 0 0]
[0 1 2 3 0 0 0 0 0 0 0 0]
[0 1]
[0 1 0]


In [30]:
a=np.array([[5,4,6],[2,3,2]]) # sorting
print(a)
print("************")
b=np.sort(a,axis=1) # row wise sorting 
print(b)
print("************")
c=np.sort(a,axis=0) # column wise sorting
print(c)

[[5 4 6]
 [2 3 2]]
************
[[4 5 6]
 [2 2 3]]
************
[[2 3 2]
 [5 4 6]]


In [31]:
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [32]:
a=np.array([4,3,2,1])
print(np.argsort(a))
print(a.argsort()) # both are same it will retuen the indices


[3 2 1 0]
[3 2 1 0]


In [33]:
a[a.argsort()]

array([1, 2, 3, 4])

In [34]:
np.sum(a,axis=0)

10

In [35]:
a=np.array([[5,4,6],[2,3,2]])
print(a)
print("****************")
print(np.sum(a,axis=0)) #column wise sum
print("****************")
print(np.sum(a,axis=1)) # row wise sum

[[5 4 6]
 [2 3 2]]
****************
[7 7 8]
****************
[15  7]


In [36]:
print(a)
print(a.min())
print(a.max())
print(a.argmin()) # return  the index of the min value in matrix a (0,1,2,3,4,5)
print(a.argmax()) # return the index of the max value in matrix a  (0,1,2,3,4,5,6)

[[5 4 6]
 [2 3 2]]
2
6
3
2


In [37]:
print(np.all(a)) # return true if all elemnts in array are non zero
print(np.any(a)) # return true atleast one of the element is non zero

True
True


In [38]:
a[1]=0 # 1st row all elemnts become zero
print(a)
print("***********")
print(np.all(a))    # we dont have  all elemnts in the array  are non zero
print("***********")
print(np.any(a)) # we have non zero elemnts in the array

[[5 4 6]
 [0 0 0]]
***********
False
***********
True


In [39]:
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [40]:
np.sqrt(x)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894]])

In [41]:
a=np.tile(np.arange(0,40,10),3) #starting from 0 stepsize is 10 maximu is 40 ---repeat 3 times
print(a)

[ 0 10 20 30  0 10 20 30  0 10 20 30]


In [42]:
a=np.tile(np.arange(0,120,10),3)  #starting from 0 stepsize is 10 maximu is 120 ---repeat 3 times
print(a)
print(a.shape)

[  0  10  20  30  40  50  60  70  80  90 100 110   0  10  20  30  40  50
  60  70  80  90 100 110   0  10  20  30  40  50  60  70  80  90 100 110]
(36,)


In [43]:
a=a.T
print(a)
print(a.shape)

[  0  10  20  30  40  50  60  70  80  90 100 110   0  10  20  30  40  50
  60  70  80  90 100 110   0  10  20  30  40  50  60  70  80  90 100 110]
(36,)


In [44]:
# now conversion from one dimensional to any dimensional by using reshape
print(a)
a=np.reshape(a,(12,3))
print(a)

[  0  10  20  30  40  50  60  70  80  90 100 110   0  10  20  30  40  50
  60  70  80  90 100 110   0  10  20  30  40  50  60  70  80  90 100 110]
[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]
 [  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]
 [  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]


In [45]:
np.random.rand(4) #generating random numbers

array([0.53721295, 0.81363028, 0.24690172, 0.1448408 ])

In [46]:
np.random.randn(4) #Return a sample from the “standard normal” distribution

array([-0.34548724, -0.08254303,  0.20523209, -0.64638397])

In [47]:
a=np.arange(10) #default dtype int32 bytes
print(a)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
int32


In [48]:
a=np.arange(10,dtype='float64')
print(a.dtype)

float64


In [49]:
a=np.eye(3,3) # identity matrix
print(a)
print(a.dtype)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
float64


In [50]:
a=np.random.randint(0,20,15) #Return random integers from low (inclusive) to high (exclusive).
print(a)
print(len(a))

[16  4 13 16  5  0 12 12 15 18 17  5 13  0 15]
15


In [51]:
p=np.identity(4) # identy matrix
print(p)
print(p.shape)

print(np.eye(4)) # identy matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [52]:
np.diag([1,1,1],2) #diagonal matrix starts from after 2 rows 

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [53]:
np. diag([2,2,2,2],1) #diagonal matrix starts from first 1st row

array([[0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 2],
       [0, 0, 0, 0, 0]])

In [54]:
np.diag([3,3,3,3,3],0) #diagonal matrix 

array([[3, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 3]])

In [55]:
np.diag([1,1,1],2) +np. diag([2,2,2,2],1) + np.diag([3,3,3,3,3],0)

array([[3, 2, 1, 0, 0],
       [0, 3, 2, 1, 0],
       [0, 0, 3, 2, 1],
       [0, 0, 0, 3, 2],
       [0, 0, 0, 0, 3]])

In [56]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [57]:
mat1=np.arange(1,5)
print(mat1)
print(mat1.shape)

[1 2 3 4]
(4,)


In [58]:
np.diag(mat1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [59]:
mat2=np.arange(5,8)
print(mat2)
print(mat2.shape)

[5 6 7]
(3,)


In [60]:
np.diag(mat2,1)+np.diag(mat1,0)

array([[1, 5, 0, 0],
       [0, 2, 6, 0],
       [0, 0, 3, 7],
       [0, 0, 0, 4]])

In [61]:
from scipy.sparse import diags
import numpy as np
n = 100
k = np.array([np.ones(n-1),-2 *np.ones(n),np.ones(n-1)])
print(k)
loc= [-1,0,1]
A = diags(k,loc).toarray()
A
#A=100**2/4(math.pi)**2*A
print(A)

[array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
 array([-2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2., -2.,
       -2., -2., -2., -2., -2., -2., -2., -2., -2.])
 a

In [62]:
np.linspace(1,5,20) # generating 20 values between 1 to 5 (equally)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [63]:
np.pi

3.141592653589793

In [64]:
x=np.arange(10)
print(x[1:8:1]) #starting from index 1 to 7 ,step size 1
print(x[5:]) # staring from index 5 to end of the index
print(x[:8]) #staring from index 0 to index 7
print(x[::-1]) #reverse order 

[1 2 3 4 5 6 7]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7]
[9 8 7 6 5 4 3 2 1 0]


### Copies and views

In [65]:
a=np.arange(10)
print(a)
b=a[::2] #array a with stepsize 2
print(b)

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


In [66]:
np.shares_memory(a,b) # numpy is memory efficient so it shares the memory with a does not create new memory for b

True

In [67]:
l1=[1,2,4,5,6]
l2=l[::2]

In [68]:
np.shares_memory(l1,l2) # list is memory inefficient so it create new memory for list l2

False

## Fancy Index

In [69]:
a=np.random.randint(0,20,15)
print(a)

[ 9 16  7  7  9 10  3 14 11 16 15  7 12 13 12]


In [70]:
print(a)
mask=(a%2==0)
extract=a[mask] #return the elements which satisfies the condition
print(extract)

[ 9 16  7  7  9 10  3 14 11 16 15  7 12 13 12]
[16 10 14 16 12 12]


In [71]:
a[mask]=-1 #satisfied elements of "a" with mask condition replace with -1 
print(a)

[ 9 -1  7  7  9 -1  3 -1 11 -1 15  7 -1 13 -1]
